image: registry.gitlab.com/junte/docker-hub/docker:19
variables:
  DOCKER_CACHE_IMAGE: $CI_REGISTRY_IMAGE/cache
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE/tmp:${CI_PIPELINE_IID}_${CI_COMMIT_SHA}
  DOCKER_TEST_IMAGE: $CI_REGISTRY_IMAGE/tmp:${CI_PIPELINE_IID}_${CI_COMMIT_SHA}_test

stages:
  - lint_dockerfile
  - build
  - test
  - publish
  - deploy

lint_dockerfile:
  stage: lint_dockerfile
  image: registry.gitlab.com/junte/docker-hub/hadolint/hadolint:v1.19.0-44-gf364c91-debian
  script:
    - hadolint deploy/Dockerfile

.base_build:
  stage: build
  services:
    - registry.gitlab.com/junte/docker-hub/docker:19-dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker pull $DOCKER_CACHE_IMAGE || true

build:
  extends: .base_build
  except:
    - mocks
  script:
    - APP_VERSION=$(cat VERSION)
    - docker build --cache-from $DOCKER_CACHE_IMAGE --target build -t $DOCKER_CACHE_IMAGE -t $DOCKER_TEST_IMAGE -f deploy/Dockerfile .
    - docker build --cache-from $DOCKER_CACHE_IMAGE --target production -t $DOCKER_IMAGE  --build-arg APP_VERSION=${APP_VERSION} -f deploy/Dockerfile .
    - docker push $DOCKER_IMAGE
    - docker push $DOCKER_CACHE_IMAGE
    - docker push $DOCKER_TEST_IMAGE

build_mocks:
  extends: .base_build
  only:
    - mocks
  script:
    - docker build --cache-from $DOCKER_CACHE_IMAGE --target production -t $DOCKER_IMAGE --build-arg BUILD_COMMAND="npm run build:mocks" --build-arg APP_VERSION=${APP_VERSION} -f deploy/Dockerfile .
    - docker push $DOCKER_IMAGE

e2e:
  stage: test
  image: $DOCKER_TEST_IMAGE
  variables:
    GIT_STRATEGY: none
  except:
    - mocks
  before_script:
    # Add Google Chrome to aptitude's (package manager) sources
    - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | tee -a /etc/apt/sources.list
    # Fetch Chrome's PGP keys for secure installation
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    # Update aptitude's package sources
    - apt-get -qq update -y
    # Install latest Chrome stable, Xvfb packages
    - apt-get -qq install -y google-chrome-stable xvfb gtk2-engines-pixbuf xfonts-cyrillic xfonts-100dpi xfonts-75dpi xfonts-base xfonts-scalable imagemagick x11-apps default-jre
    # Launch Xvfb
    - Xvfb :0 -ac -screen 0 1024x768x24 &
    # Export display for Chrome
    - export DISPLAY=:99
    # Download Selenium server JAR, drivers for Chrome
    - /src/node_modules/.bin/webdriver-manager update
  script:
    - cd /src
    - npm run e2e

.base_publish:
  stage: publish
  dependencies: []
  services:
    - registry.gitlab.com/junte/docker-hub/docker:19-dind
  variables:
    GIT_STRATEGY: none
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker pull $DOCKER_IMAGE
  script:
    - docker tag $DOCKER_IMAGE $TARGET_IMAGE
    - docker push $TARGET_IMAGE

publish_unstable:
  extends: .base_publish
  only:
    - master
  variables:
    TARGET_IMAGE: $CI_REGISTRY_IMAGE/unstable:${CI_PIPELINE_ID}

publish_mocks:
  extends: .base_publish
  only:
    - mocks 
  variables:
    TARGET_IMAGE: $CI_REGISTRY_IMAGE/mocks:${CI_PIPELINE_ID}

publish_stable:
  extends: .base_publish
  only:
    - tags
  variables:
    TARGET_IMAGE: $CI_REGISTRY_IMAGE/stable:${CI_COMMIT_TAG}

.base_deploy:
  image: registry.gitlab.com/junte/docker-hub/curl:7.72.0
  stage: deploy
  dependencies: []
  script:
    - curl -k -X POST -d "component=${DEPLOYER_COMPONENT}&key=${DEPLOYER_KEY}&tag=${CI_PIPELINE_ID}" ${DEPLOYER_HOST}

deploy_development:
  extends: .base_deploy
  only:
    - master
  environment:
    name: development
    url: $SITE_ADDRESS

deploy_mocks:
  extends: .base_deploy
  only:
    - mocks
  environment:
    name: mocks
    url: $SITE_ADDRESS
  